[package]
name = "draw-it"
version = "0.1.0"
authors = ["Oliver Berzs <oliver.berzs@gmail.com>"]
edition = "2018"

[[bin]]
name = "dic"
path = "src/dic.rs"

[features]
default = ["window", "png", "glsl"]
glsl = ["shaderc"]
window = ["winit"]
log = []

# optional dependencies
[dependencies]
winit = { version = "0.23.0", optional = true }
png = { version = "0.16.7", default-features = false, optional = true }
shaderc = { version = "0.6.2", optional = true }
