[workspace]
members = [
  "tegne",
  "import",
  "examples/blue",
  "examples/gradient",
  "examples/cubes",
  "examples/surface",
  "examples/dynamic",
  "examples/ui",
  "examples/textures",
  "examples/toon",
  "examples/blur"
]
